# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18520957a899afbe5da09bc0aeb999c60f3e999a6cb293d21fd9130285c9095b525f10c1639dbc88697177d58200211de525123c3dfe2e19e91bc25ce519f765

test:
  secret_key_base: e96f0e0229774b2f3100a207c0f04b8f36725a6cc9595eb811aded619187c43c5320e98a8bca6b142f42ed0a0513e8b3bf49f2ba08eac9d6c86a47c87e6021e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
